= JLex

* Es un generador de analizadores léxicos basado en Lex pero escrito en Java.
* Es capaz de generar automáticamente un analizador léxico a partir de una especificación léxica, estos archivos suelen tener la extension .lex o .jlex, 
igualmente se trata de un simple archivo de texto que contiene el conjunto de directivas/reglas que deben ser tenidas en cuenta para el lenguaje especificado.
* Para utilizarlo simplemente debemos descargarlo de su https://www.cs.princeton.edu/~appel/modern/java/JLex/[página Web], y esto nos descarga un 
archivo Java que tiene la implementación del generador, luego debemos compilar ese archivo Java, y luego usarlo para procesar nuestra especificación léxica, 
nosotros usaremos un plugin de Maven para agilizar este proceso.
* Luego debemos empezar a escribir nuestra especificación para luego ejecutar jlex usando la misma como input (Ya sea de forma manual o con el maven plugin).
* El archivo de especificación léxica, contiene distintas partes las cuales comentaremos en el archivo lexer.jlex