
package ar.com.javacuriosities.facade.api.clients.legacy.utils;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ProductsWS", targetNamespace = "http://api.legacy.javacuriosities.com.ar/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ProductsWS {


    /**
     * 
     * @return
     *     returns java.util.List<ar.com.javacuriosities.facade.api.clients.legacy.utils.Product>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "products", targetNamespace = "http://api.legacy.javacuriosities.com.ar/", className = "ar.com.javacuriosities.facade.api.clients.legacy.utils.Products")
    @ResponseWrapper(localName = "productsResponse", targetNamespace = "http://api.legacy.javacuriosities.com.ar/", className = "ar.com.javacuriosities.facade.api.clients.legacy.utils.ProductsResponse")
    @Action(input = "http://api.legacy.javacuriosities.com.ar/ProductsWS/productsRequest", output = "http://api.legacy.javacuriosities.com.ar/ProductsWS/productsResponse")
    public List<Product> products();

}
