package ar.com.javacuriosities.facade.api.clients.legacy.utils;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebServiceClient(name = "ProductsWS", targetNamespace = "http://api.legacy.javacuriosities.com.ar/")
public class ProductsWS_Service
        extends Service {

    private final static URL PRODUCTSWS_WSDL_LOCATION;
    private final static WebServiceException PRODUCTSWS_EXCEPTION;
    private final static QName PRODUCTSWS_QNAME = new QName("http://api.legacy.javacuriosities.com.ar/", "ProductsWS");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://" + System.getenv("LEGACY_HOST") + "/legacy/ProductsWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PRODUCTSWS_WSDL_LOCATION = url;
        PRODUCTSWS_EXCEPTION = e;
    }

    public ProductsWS_Service() {
        super(__getWsdlLocation(), PRODUCTSWS_QNAME);
    }

    public ProductsWS_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), PRODUCTSWS_QNAME, features);
    }

    public ProductsWS_Service(URL wsdlLocation) {
        super(wsdlLocation, PRODUCTSWS_QNAME);
    }

    public ProductsWS_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PRODUCTSWS_QNAME, features);
    }

    public ProductsWS_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProductsWS_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    private static URL __getWsdlLocation() {
        if (PRODUCTSWS_EXCEPTION != null) {
            throw PRODUCTSWS_EXCEPTION;
        }
        return PRODUCTSWS_WSDL_LOCATION;
    }

    /**
     * @return returns ProductsWS
     */
    @WebEndpoint(name = "ProductsWSPort")
    public ProductsWS getProductsWSPort() {
        return super.getPort(new QName("http://api.legacy.javacuriosities.com.ar/", "ProductsWSPort"), ProductsWS.class);
    }

    /**
     * @param features A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns ProductsWS
     */
    @WebEndpoint(name = "ProductsWSPort")
    public ProductsWS getProductsWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://api.legacy.javacuriosities.com.ar/", "ProductsWSPort"), ProductsWS.class, features);
    }

}
