//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.29 at 07:56:14 AM ART 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.javacuriosities.com.ar/schema", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ar.com.javacuriosities.schema;
