= JLex-CUP

* En este proyecto utilizaremos JLex y CUP para construir un analizador léxico y sintáctico para un lenguaje sencillo, con el cual se podrán hacer operaciones aritméticas como sumar, restar, multiplicar y dividir.
* En nuestro proyecto JLex usamos un plugin de Maven para ejecutar JLex ahora vamos a ejecutarlo de forma manual tanto JLex como JavaCup.
* JavaCUP genera parsers que utilizan el algoritmo LALR (Look ahead left right), o sea la lectura se hace de izquierda a derecha y las derivaciones a derecha, en este tipo de algoritmos el árbol de derivación desde las hojas, hacia la raíz
* Diferencia entre derivación izquierda vs derecha

Gramática
+++++++++

<Asignacion> ::= <Id> = <Expresion>
	 
<Id> ::= A | B | C

<Expresion> ::= <Expresion> + <Term> | <Term>

<Term> ::= <Term> * <Factor> | <Factor>

<Factor> ::= ( <Expresion> ) | <Id>

Utilizando la gramática anterior vamos a analizar ambos tipos de derivaciones para la siguiente expresión

A = B + C * A

----
Derivación izquierda (Left Most Derivation)

<Asignacion> => <Id> = <Expresion>
		=> A = <Expresion> + <Term>
              	=> A = <Term> + <Term>  
              	=> A = <Factor> + <Term> 
              	=> A = <Id> + <Term> 
              	=> A = B + <Term> 
              	=> A = B + <Term> * <Factor>
              	=> A = B + <Factor> * <Factor>
              	=> A = B + <Id> * <Factor>
              	=> A = B + C * < Term>
              	=> A = B + C * <Factor>
              	=> A = B + C * <Id>
              	=> A = B + C * A

Derivación derecha (Right Most Derivation)

<Asignacion> => <Id> = <Expresion>
			=> <Id> = <Expresion> + <Term>
			=> <Id> = <Expresion> + <Term> * <Factor>
			=> <Id> = <Expresion> + <Term> * <Id>
			=> <Id> = <Expresion> + <Term> * A
			=> <Id> = <Expresion> + <Factor> * A
			=> <Id> = <Expresion> + <Id> * A
			=> <Id> = <Expresion> + C * A
			=> <Id> = <Term> + C * A
			=> <Id> = <Id> + C * A
			=> <Id> = B + C * A
			=>  A = B + C * C
